from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from adiabaticlimit import AdiabaticPhaseDiagram
from plot_bohr_domain_visibility_map import ALPHA_REF, E_RES, Q_REF, Z_LZ_REF, c_out_from_z


BASE_DIR = Path(__file__).resolve().parent
DIAG_DIR = BASE_DIR / "diagnostics"
CSV_PATH = DIAG_DIR / "bohr_domain_scaling_validation.csv"
SUMMARY_PATH = DIAG_DIR / "bohr_domain_scaling_validation.md"


SAMPLE_ALPHAS = [0.10, 0.16, 0.20, 0.26, 0.30, 0.35]
SAMPLE_QS = [1.0e-6, 1.0e-5, 1.0e-4, 1.0e-3]


def scaled_z(alpha: float, q: float) -> float:
    return float(Z_LZ_REF * (q / Q_REF) * (alpha / ALPHA_REF) ** (-5.0))


def main() -> None:
    DIAG_DIR.mkdir(parents=True, exist_ok=True)
    diagram = AdiabaticPhaseDiagram(
        initial_state=(6, 4, 4),
        final_state=(5, 4, 4),
        resonance_harmonic=1,
        eccentricity=E_RES,
    )

    rows = []
    for alpha in SAMPLE_ALPHAS:
        for q in SAMPLE_QS:
            direct = float(diagram.compute_z_parameter(alpha, q, M_bh_solar=1.0))
            scale = scaled_z(alpha, q)
            rows.append(
                {
                    "alpha": alpha,
                    "q": q,
                    "z_direct_finite_fourier": direct,
                    "z_reference_scaling": scale,
                    "z_ratio_scaling_over_direct": scale / direct if direct > 0.0 else np.nan,
                    "c_direct": float(c_out_from_z(np.asarray(direct))),
                    "c_scaling": float(c_out_from_z(np.asarray(scale))),
                }
            )

    with CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    ratios = np.asarray([row["z_ratio_scaling_over_direct"] for row in rows], dtype=float)
    finite_ratios = ratios[np.isfinite(ratios) & (ratios > 0.0)]
    max_log10 = float(np.max(np.abs(np.log10(finite_ratios)))) if finite_ratios.size else np.nan

    lines = [
        "# Bohr domain scaling validation",
        "",
        "Generated by `probe_bohr_domain_scaling_validation.py`.",
        "",
        "This compares the reference-point scaling used in `plot_bohr_domain_visibility_map.py` with the direct finite-separation Fourier estimate implemented in `adiabaticlimit.py`.",
        "",
        "| alpha | q | z direct | z scaling | scaling/direct | C direct | C scaling |",
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| {row['alpha']:.3g} | {row['q']:.1e} | "
            f"{row['z_direct_finite_fourier']:.6g} | {row['z_reference_scaling']:.6g} | "
            f"{row['z_ratio_scaling_over_direct']:.6g} | {row['c_direct']:.6g} | {row['c_scaling']:.6g} |"
        )
    lines.extend(
        [
            "",
            f"Maximum absolute log10 ratio over the sparse grid: `{max_log10:.3g}` dex.",
            "",
            "Verdict: the reference scaling preserves the qualitative branch structure near the reference point, but it is not a substitute for a point-by-point finite-separation Fourier scan.  It should be described as a normalized domain estimate.  The supplemental phase diagram remains the direct finite-separation Fourier calculation.",
            "",
            f"CSV: `{CSV_PATH.as_posix()}`",
        ]
    )
    SUMMARY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {CSV_PATH}")
    print(f"Wrote {SUMMARY_PATH}")


if __name__ == "__main__":
    main()
