from __future__ import annotations

from pathlib import Path

import numpy as np

import highfre644
from adiabaticlimit import AdiabaticPhaseDiagram


Q_REF = 1.0e-2
E_REF = 0.64
M1_MSUN = 1.0
CLOUD_MASS_FRACTION = 0.005
OUTPUT_PATH = Path("diagnostics") / "bohr_q001_boundary_probe.txt"


def roche_lobe_fraction_primary(q: float) -> float:
    """Eggleton Roche-lobe radius around the primary, divided by separation."""
    mass_ratio_primary_to_secondary = 1.0 / float(q)
    q23 = mass_ratio_primary_to_secondary ** (2.0 / 3.0)
    q13 = mass_ratio_primary_to_secondary ** (1.0 / 3.0)
    return 0.49 * q23 / (0.6 * q23 + np.log(1.0 + q13))


def lz_probability(z_lz: float) -> tuple[float, float]:
    p_lz = 1.0 - np.exp(-2.0 * np.pi * float(z_lz))
    coherence = np.sqrt(max(p_lz * (1.0 - p_lz), 0.0))
    return p_lz, coherence


def radial_probability_peak(diagram: AdiabaticPhaseDiagram, state: tuple[int, int, int]) -> float:
    x = np.logspace(-4, 3.0, 20000)
    radial = diagram._radial_wavefunction_dimensionless(state, x)
    density = x**2 * np.abs(radial) ** 2
    return float(x[int(np.argmax(density))])


def find_alpha_for_z(diagram: AdiabaticPhaseDiagram, target_z: float = 1.0) -> tuple[float, dict[str, float]]:
    alphas = np.linspace(0.18, 0.35, 600)
    components = [
        diagram.compute_z_components(float(alpha), Q_REF, M_bh_solar=M1_MSUN, eccentricity=E_REF)
        for alpha in alphas
    ]
    z_values = np.array([entry["z"] for entry in components], dtype=float)
    idx = int(np.argmin(np.abs(z_values - target_z)))
    return float(alphas[idx]), components[idx]


def run_waveform_probe(alpha: float) -> dict[str, float]:
    sim = highfre644.EccentricResonantTidalGA(
        M_bh=M1_MSUN,
        M_star=Q_REF * M1_MSUN,
        alpha=alpha,
        bh_spin=0.7,
        distance_Mpc=0.001,
        z=0.0,
        e_init=0.65,
        cloud_mass_fraction=CLOUD_MASS_FRACTION,
        save_frequency_data_dir=None,
        save_time_series_data_dir=None,
        save_figure_dir="figures",
    )
    duration_yr = sim.recommended_duration_to_cover_selected_resonance(
        initial_duration_yr=2.0e-4,
        max_duration_yr=5.0e-2,
        post_event_padding_orbits=180.0,
    )
    results = sim.run(
        duration_yr=duration_yr,
        secular_samples=900,
        zoom_orbits=18,
        zoom_points=4096,
        spectrum_orbits=80,
        spectrum_points=4096,
        spectrum_pad_factor=2,
        save_exports=False,
    )
    events = list(results["cloud"].get("local_lz_events", []))
    if not events:
        raise RuntimeError("No selected LZ event found in waveform probe.")
    event = events[0]
    orbit = results["orbit"]
    t_event = float(event["t_source"])
    a_event = float(np.interp(t_event, orbit["t"], orbit["a"]))
    r0 = sim.r_c
    p_lz, coherence = lz_probability(float(event["z_ad"]))
    return {
        "alpha": float(alpha),
        "duration_yr": float(duration_yr),
        "transition_frequency_hz": float(sim.transition_frequency_hz),
        "f_orb_init_hz": float(sim.f_orb_init),
        "z_event": float(event["z_ad"]),
        "p_lz": p_lz,
        "coherence_lz": coherence,
        "dP_high": float(event.get("delta_high_population", np.nan)),
        "delta_a_over_a": float(event.get("delta_a_over_a", np.nan)),
        "delta_e": float(event.get("delta_e", np.nan)),
        "a_over_r0": a_event / r0,
    }


def main() -> None:
    diagram = AdiabaticPhaseDiagram(
        initial_state=(6, 4, 4),
        final_state=(5, 4, 4),
        resonance_harmonic=1,
        eccentricity=E_REF,
    )
    alpha_boundary, boundary = find_alpha_for_z(diagram, target_z=1.0)
    alpha_show = [0.20, 0.22, alpha_boundary, 0.25, 0.30]
    roche_fraction = roche_lobe_fraction_primary(Q_REF)
    peak_initial = radial_probability_peak(diagram, (6, 4, 4))
    peak_final = radial_probability_peak(diagram, (5, 4, 4))
    peak_outer = max(peak_initial, peak_final)

    rows = []
    for alpha in alpha_show:
        comp = diagram.compute_z_components(float(alpha), Q_REF, M_bh_solar=M1_MSUN, eccentricity=E_REF)
        p_lz, coherence = lz_probability(comp["z"])
        rows.append(
            {
                "alpha": float(alpha),
                "z": float(comp["z"]),
                "p_lz": p_lz,
                "coherence": coherence,
                "a_over_r0": float(comp["x_star"]),
                "a_over_outer_peak": float(comp["x_star"] / peak_outer),
                "a_over_roche_outer_peak": float(comp["x_star"] * roche_fraction / peak_outer),
                "tidal_small": float(Q_REF / comp["x_star"] ** 3),
            }
        )

    waveform = run_waveform_probe(alpha_boundary)

    lines = [
        "# q=0.01 Bohr boundary probe",
        "",
        "This file was generated by `probe_bohr_q001_boundary.py`.",
        "",
        f"Reference setup: `q={Q_REF:g}`, `e_res={E_REF:g}`, `M1={M1_MSUN:g} Msun`, transition `|644> -> |544>` with selected `n=1` harmonic.",
        "",
        "## Boundary estimate",
        "",
        f"The closest sampled point to `z_LZ=1` is `alpha={alpha_boundary:.5f}`, with `z_LZ={boundary['z']:.5f}`.",
        "This is the cleanest q=1/100 benchmark for a crossing that is close to adiabatic quenching but still leaves finite Landau-Zener coherence.",
        "",
        "## Scan table",
        "",
        "| alpha | z_LZ | P_LZ | C_LZ=sqrt(P(1-P)) | a/r0 | a/r_peak,max | R_L1/r_peak,max | q/(a/r0)^3 |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            "| {alpha:.5f} | {z:.4f} | {p_lz:.4f} | {coherence:.4f} | "
            "{a_over_r0:.2f} | {a_over_outer_peak:.3f} | {a_over_roche_outer_peak:.3f} | {tidal_small:.3e} |".format(
                **row
            )
        )

    lines.extend(
        [
            "",
            "Here `r0=GM1/(alpha^2 c^2)`, while `r_peak,max` is the larger radial probability peak of the two hydrogenic levels in units of `r0`.",
            "The small local tidal parameter `q/(a/r0)^3` is safely tiny, but the Roche/multipole condition is more delicate because the high-n cloud radius is comparable to the resonance separation.",
            "",
            "## Time-domain check at the boundary point",
            "",
            "| quantity | value |",
            "| --- | ---: |",
        ]
    )
    for key in (
        "alpha",
        "transition_frequency_hz",
        "f_orb_init_hz",
        "duration_yr",
        "z_event",
        "p_lz",
        "coherence_lz",
        "dP_high",
        "delta_a_over_a",
        "delta_e",
        "a_over_r0",
    ):
        lines.append(f"| `{key}` | {waveform[key]:.8e} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `alpha~0.238` is better than `alpha=0.30` if the paper needs a q=1/100 example that is close to the quenching boundary.",
            "- The high-n Bohr pair makes the cloud-size validity condition the limiting issue, not the small local tidal parameter.",
            "- A conservative paper should describe the q=0.1 orbit-time plot as a morphology illustration only, and use q=0.01 for quantitative claims.",
        ]
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print("\n".join(lines[:18]))


if __name__ == "__main__":
    main()
